name: Release Manually
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'which docker build to run'
        required: true
        default: 'opengauss'
        type: choice
        options:
          - 'opengauss'
      upstream-ref:
        description: 'upstream ref'
        required: false
        default: ''
        type: string
      tag:
        description: 'tag'
        required: true
        default: 'v6.0.0-ubuntu24.04'
        type: string
env:
  ONLINE_REGISTER: ghcr.io/usernameisnull
  BUILD_PLATFORM: linux/amd64
jobs:
  opengauss:
    if: ${{ inputs.job == 'opengauss' }}
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build && Push
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./6.0.0
          file: ./6.0.0/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
            ${{ env.ONLINE_REGISTER }}/opengauss:${{ inputs.tag }}
            ${{ env.ONLINE_REGISTER }}/opengauss:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max